version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-iot
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: iot_data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend-iot
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: iot_data
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend-iot
    ports:
      - "3000:80"
    depends_on:
      - backend
