apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: StatefulSet
      name: postgres
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: gp2
  - target:
      kind: Ingress
      name: agrinexus
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: app.agrinexus.aws.example
      - op: replace
        path: /spec/rules/1/host
        value: api.agrinexus.aws.example
