apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agrinexus
  namespace: agrinexus
spec:
  ingressClassName: nginx
  rules:
    - host: app.agrinexus.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: api.agrinexus.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000
